### PR TITLE
Issue #3032672 by truls1502: Restricted area for robots to drupal.no until we released the website

### PR DESCRIPTION
**Pull request by truls1502**
## Problem & Solution
Restricted area for robots to drupal.no until we released the website

## Issue tracker
https://www.drupal.org/project/drupal_norway/issues/3032672

### CODE REVIEW

**Comment by truls1502** [comment]
What do you think @falster and @eiriksm?

**Comment by falster** [comment]
Denne ble vel med i den andre? Så da lukker jeg den.

**Comment by truls1502** [comment]
Den andre hva? Jeg kan ikke se andre issue/PR? 😊

**Comment by truls1502** [comment]
@falster tenkte du på den #6? Hvis ja, så er det ikke det samme 😊

**Pull request merged**
